#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-diff-lcs
Version  : 1.2.5
Release  : 6
URL      : https://rubygems.org/downloads/diff-lcs-1.2.5.gem
Source0  : https://rubygems.org/downloads/diff-lcs-1.2.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: rubygem-diff-lcs-bin
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-hoe
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubyforge

%description
= Diff::LCS
home :: http://diff-lcs.rubyforge.org/
code :: https://github.com/halostatue/diff-lcs
bugs :: https://github.com/halostatue/diff-lcs/issues
rdoc :: http://rubydoc.info/github/halostatue/diff-lcs

%package bin
Summary: bin components for the rubygem-diff-lcs package.
Group: Binaries

%description bin
bin components for the rubygem-diff-lcs package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n diff-lcs-1.2.5
gem spec %{SOURCE0} -l --ruby > rubygem-diff-lcs.gemspec

%build
gem build rubygem-diff-lcs.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
diff-lcs-1.2.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/diff-lcs-1.2.5
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/diff-lcs-1.2.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/.hoerc
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/Contributing.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/History.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/License.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/autotest/discover.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/bin/htmldiff
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/bin/ldiff
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/docs/COPYING.txt
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/docs/artistic.txt
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff-lcs.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/block.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/change.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/htmldiff.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/hunk.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/internals.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/ldiff.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib/diff/lcs/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/change_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/diff_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/hunk_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/issues_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/lcs_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/patch_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/sdiff_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/traverse_balanced_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/spec/traverse_sequences_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/diff-lcs-1.2.5.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/htmldiff
/usr/bin/ldiff
