#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-diff-lcs
Version  : 1.2.5
Release  : 4
URL      : https://rubygems.org/downloads/diff-lcs-1.2.5.gem
Source0  : https://rubygems.org/downloads/diff-lcs-1.2.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: rubygem-diff-lcs-bin
BuildRequires : ruby
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-hoe
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubyforge

%description
= Diff::LCS
home :: http://diff-lcs.rubyforge.org/
code :: https://github.com/halostatue/diff-lcs
bugs :: https://github.com/halostatue/diff-lcs/issues
rdoc :: http://rubydoc.info/github/halostatue/diff-lcs

%package bin
Summary: bin components for the rubygem-diff-lcs package.
Group: Binaries

%description bin
bin components for the rubygem-diff-lcs package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n diff-lcs-1.2.5
gem spec %{SOURCE0} -l --ruby > rubygem-diff-lcs.gemspec

%build
gem build rubygem-diff-lcs.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
diff-lcs-1.2.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/diff-lcs-1.2.5
rspec spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/diff-lcs-1.2.5.gem
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/BalancedCallbacks/cdesc-BalancedCallbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/BalancedCallbacks/change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/BalancedCallbacks/discard_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/BalancedCallbacks/discard_b-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/BalancedCallbacks/match-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/cdesc-Block.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/changes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/diff_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/insert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/op-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Block/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/action-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/adding%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/cdesc-Change.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/changed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/deleting%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/finished_a%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/finished_b%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/from_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/position-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/unchanged%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Change/valid_action%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/cdesc-ContextChange.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/from_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/new_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/new_position-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/old_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/old_position-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/simplify-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextChange/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextDiffCallbacks/cdesc-ContextDiffCallbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextDiffCallbacks/change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextDiffCallbacks/discard_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/ContextDiffCallbacks/discard_b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DefaultCallbacks/cdesc-DefaultCallbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DefaultCallbacks/change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DefaultCallbacks/discard_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DefaultCallbacks/discard_b-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DefaultCallbacks/match-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/cdesc-DiffCallbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/diffs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/discard_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/discard_b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/finish_hunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/DiffCallbacks/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/cdesc-Callbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/discard_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/discard_b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/htmlize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/match_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/only_a_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/only_b_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/Callbacks/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/cdesc-HTMLDiff.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/HTMLDiff/verify_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/blocks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/cdesc-Hunk.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/context_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/context_range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/ed_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/encode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/encode_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/end_new-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/end_old-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/file_length_difference-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/flag_context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/old_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/overlaps%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/start_new-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/start_old-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/unified_diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/unified_range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Hunk/unshift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Internals/cdesc-Internals.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/LCS-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/Ldiff/cdesc-Ldiff.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/cdesc-SDiffCallbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/diffs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/discard_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/discard_b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SDiffCallbacks/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SequenceCallbacks/cdesc-SequenceCallbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SequenceCallbacks/change-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SequenceCallbacks/discard_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SequenceCallbacks/discard_b-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/SequenceCallbacks/match-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/callbacks_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/cdesc-LCS.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/diff-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/diff_traversal-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/lcs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/lcs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/patch%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/patch%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/patch-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/patch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/patch_me-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/sdiff-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/sdiff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/traverse_balanced-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/traverse_balanced-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/traverse_sequences-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/traverse_sequences-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/unpatch%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/unpatch%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/unpatch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/LCS/unpatch_me-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/Diff/cdesc-Diff.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/docs/page-COPYING_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/docs/page-artistic_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/page-Contributing_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/page-History_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/page-License_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/diff-lcs-1.2.5/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/.hoerc
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/Contributing.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/License.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/autotest/discover.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/bin/htmldiff
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/bin/ldiff
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/docs/COPYING.txt
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/docs/artistic.txt
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff-lcs.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/array.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/block.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/callbacks.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/change.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/htmldiff.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/hunk.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/internals.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/ldiff.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib/diff/lcs/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/change_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/diff_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/hunk_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/issues_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/lcs_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/patch_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/sdiff_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/traverse_balanced_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/spec/traverse_sequences_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/diff-lcs-1.2.5.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/htmldiff
/usr/bin/ldiff
